language: python
python:
  - "2.6"
  - "2.7"
before_script: sudo apt-get install pychecker
install: pip install -r requirements --use-mirrors
script: pyb
notifications:
  email:
    - halimath.wilanthaou@googlemail.com

